# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Docs
    url: /docs/
    weight: 20
  - name: Community
    url: /community/
    weight: 30
